### ISSUE TITLE
Not an issue, just a thanks!

### ISSUE THREAD

**Issue by opensourcegeek** [uiiaoo/java-syntax.vim#1]
Thanks for sharing this syntax file, I've been looking around to see if I could get a nicer syntax file than the builtin one. Your plugin looks great in my setup, so just wanted to say thanks! Unfortunately GH doesn't have a 'Send a thanks' button...

**Comment by uiiaoo** [comment]
Thank you :)
If you have any dissatisfaction with this plugin, please share with me.
