### ISSUE TITLE
[Feature Request] Split Operators and Delimiters

### ISSUE THREAD

**Issue by Iron-E** [uiiaoo/java-syntax.vim#5]
Hello,

Thank you for your work on this plugin. I like this plugin's syntax highlighting much better than the default!

I have one question: would it be possible to separate the syntax groups defined for operators and delimiters?

![cap](https://user-images.githubusercontent.com/36409591/100680322-51026600-333f-11eb-8565-0d943a10c925.png)

In the above image, I have three filetypes: C#, Lua, and Java. C# and Lua define "noise" operators separately, such as:

* `.`
* `;`
* `(`, `)`
* `{`, `}`

…and things of that nature. That way, operator-keywords like `new` and operator symbols `+` can be highlighted separately from syntax delimiters. Currently, this plugin groups all of these together under one `javaOperator` syntax group. Would you be open to splitting it into `javaOperator` and `javaDelimiter` or `javaNoise`?

**Comment by uiiaoo** [comment]
Thank you for using this plugin and your suggestion :)
I apologize for not replying to you for a long time.
I agree to separate the following operators from `javaOperator`.
* `()`
* `.`
* `[]`
* `,`
* `;`
* `{}`

As for `<>`, your method is insufficient, because it cannot handle the case such as `variable>0` that I often write properly.
For this reason, I will keep `<>` as a part of `javaOperator`.

I would like to consider the group name, so could you share your C# and Lua syntax highlighting plugins with me?

**Comment by Iron-E** [comment]
No worries about taking a while to respond, I know a lot of this open-source stuff happens on a free-time basis.

> I would like to consider the group name, so could you share your C# and Lua syntax highlighting plugins with me?

Sure thing! For C#, I am using Neovim's default C# syntax file (`nvim --noplugin foo.cs -c syntax`; Vim should work too though). For Lua I am using [this plugin](https://github.com/tbastos/vim-lua).

There are other C# plugins available though, like [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim) and [vim-csharp](https://github.com/OrangeT/vim-csharp). I have used the former and know it also supports delimiter highlighting.

> As for `<>`, your method is insufficient, because it cannot handle the case such as `variable>0` that I often write properly. For this reason, I will keep `<>` as a part of `javaOperator`.

The implementation of generic detecting I put in the PR was the simplest I could come up with (both in terms of cognitive and runtime overhead) but unfortunately it can't tell the difference between operator and generic use of `>` in that case. Both `variable > 0` and `variable >0` would work here, but not `variable>0` since I believes anything without a preceding space is most definitely the ending generic delimiter (which, as we can see, is not necessarily true).

I have this working on my other plugin [rust.vim](https://github.com/Iron-E/rust.vim), but the complexity of the implementation is increased compared to this one. I could probably port it over if you were interested in trying to maintain that feature, but I'll leave it up to you!
